### ISSUE TITLE
Stylelint: order/order problematic rule

### ISSUE THREAD

**Issue by literat** [lmc-eu/code-quality-tools#190]
- https://github.com/lmc-eu/code-quality-tools/pull/180#discussion_r1723547656
- https://github.com/visionappscz/stylelint-config/discussions/63#discussioncomment-10191094

For now, leaving the block off.

**Comment by adamkudrna** [comment]
Check https://github.com/visionappscz/stylelint-config/pull/64

**Comment by literat** [comment]
Fixed in https://github.com/lmc-eu/code-quality-tools/pull/180
