### ISSUE TITLE
[@lmc-eu/conventional-changelog-lmc-github] Breaking changes missing from the changelog

### ISSUE THREAD

**Issue by OndraM** [lmc-eu/code-quality-tools#54]
The BREAKING CHANGES commits are missing from the generated changelog when using `@lmc-eu/conventional-changelog-lmc-github`.

Which is quite unfortunate :)

**Comment by literat** [comment]
Probably caused by #52

**Comment by literat** [comment]
Fixed in:
- @lmc-eu/conventional-changelog-lmc-bitbucket@2.0.4
- @lmc-eu/conventional-changelog-lmc-github@2.0.4
